(() => {
  const API=window.DELI_API_URL||"https://deligo-backend-i554.onrender.com";let drivers=[],initialized=false,selectedId='';
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const date=v=>{if(!v)return'—';const d=new Date(v);return isNaN(d)?'—':new Intl.DateTimeFormat('es-VE',{dateStyle:'medium',timeStyle:'short'}).format(d)};
  const money=(v,c='USD')=>`${Number(v||0).toFixed(2)} ${c}`;
  const auth=()=>{const t=sessionStorage.getItem('deliAdminSessionToken')||'';return{'Content-Type':'application/json',...(t?{'Authorization':`Bearer ${t}`}:{})}};
  async function req(path,opt={}){const r=await fetch(`${API}${path}`,{credentials:'include',...opt,headers:{...auth(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok||d.ok===false)throw new Error(d.message||'No se pudo completar la operación.');return d}
  const st={PENDING:'Pendiente',APPROVED:'Aprobado',SUSPENDED:'Suspendido',BLOCKED:'Bloqueado',REJECTED:'Rechazado'};
  async function load(silent=false){const box=document.getElementById('driversList');if(box&&!silent)box.innerHTML='<div class="empty-box">Cargando repartidores…</div>';try{const d=await req('/admin/drivers');drivers=d.drivers||[];stats();list();if(selectedId&&document.getElementById('driverDetailPanel')&&!document.getElementById('driverDetailPanel').classList.contains('hidden'))show(selectedId,true)}catch(e){if(box&&!silent)box.innerHTML=`<div class="empty-box error">${esc(e.message)}</div>`}}
  function stats(){const c={ALL:drivers.length,PENDING:0,APPROVED:0,AVAILABLE:0,ON_DELIVERY:0,BLOCKED:0};drivers.forEach(d=>{c[d.administrativeStatus]=(c[d.administrativeStatus]||0)+1;if(d.isAvailable)c.AVAILABLE++;if(d.operationalStatus==='ON_DELIVERY')c.ON_DELIVERY++});const b=document.getElementById('driversStats');if(b)b.innerHTML=`<article><span>Total</span><strong>${c.ALL}</strong></article><article><span>Pendientes</span><strong>${c.PENDING}</strong></article><article><span>Aprobados</span><strong>${c.APPROVED}</strong></article><article><span>Disponibles</span><strong>${c.AVAILABLE}</strong></article><article><span>En entrega</span><strong>${c.ON_DELIVERY}</strong></article><article><span>Bloqueados</span><strong>${c.BLOCKED}</strong></article>`;document.getElementById('repartidoresPendientes')&&(document.getElementById('repartidoresPendientes').textContent=c.PENDING)}
  function filtered(){const q=(document.getElementById('driversSearch')?.value||'').toLowerCase(),f=document.getElementById('driversStatusFilter')?.value||'ALL';return drivers.filter(d=>(f==='ALL'||d.administrativeStatus===f)&&(!q||[d.fullName,d.email,d.phone,d.identityDocument,d.vehiclePlate].some(v=>String(v||'').toLowerCase().includes(q))))}
  function list(){const b=document.getElementById('driversList');if(!b)return;const x=filtered();if(!x.length){b.innerHTML='<div class="empty-box">No hay repartidores.</div>';return}b.innerHTML=`<table class="admin-table drivers-directory-table"><thead><tr><th>Repartidor</th><th>Teléfono</th><th>Correo</th><th>Vehículo</th><th>Placa</th><th>Estado</th><th>Calificación</th><th>Acciones</th></tr></thead><tbody>${x.map(d=>`<tr><td class="driver-name-cell"><strong>${esc(d.fullName)}</strong><small>C.I. ${esc(d.identityDocument||'No registrada')}</small></td><td class="driver-phone-cell">${esc(d.phone||'—')}</td><td class="driver-email-cell"><span title="${esc(d.email||'')}">${esc(d.email||'—')}</span></td><td class="driver-vehicle-cell"><strong>${esc(d.vehicleType||'—')}</strong><small>${esc([d.vehicleBrand,d.vehicleModel].filter(Boolean).join(' ')||'Modelo no registrado')}</small></td><td class="driver-plate-cell">${esc(d.vehiclePlate||'—')}</td><td><span class="status-pill status-${String(d.administrativeStatus).toLowerCase()}">${esc(st[d.administrativeStatus]||d.administrativeStatus)}</span></td><td class="driver-rating-cell">⭐ ${Number(d.rating||0).toFixed(2)}</td><td><button class="driver-action view" data-view="${esc(d.id)}">Ver datos</button></td></tr>`).join('')}</tbody></table>`;b.querySelectorAll('[data-view]').forEach(e=>e.onclick=()=>show(e.dataset.view))}
  const section=(title,body,open=false)=>`<details class="driver-section" ${open?'open':''}><summary>${title}</summary><div class="driver-section-body">${body}</div></details>`;
  async function show(id,silent=false){selectedId=id;const p=document.getElementById('driverDetailPanel');if(!p)return;p.classList.remove('hidden');if(!silent)p.innerHTML='<div class="admin-panel">Cargando ficha completa…</div>';try{const d=await req(`/admin/drivers/${encodeURIComponent(id)}`),x=d.driver,s=d.summary||{},jobs=d.jobs||[],ratings=d.ratings||[],sett=d.settlements||[],requests=d.settlementRequests||[];
    const fields=['fullName','phone','identityDocument','birthDate','address','countryCode','city','zone','vehicleType','vehicleBrand','vehicleModel','vehiclePlate','vehicleColor','emergencyContact','commissionPercent'];
    const form=fields.map(k=>`<label><span>${({fullName:'Nombre completo',phone:'Teléfono',identityDocument:'Cédula',birthDate:'Nacimiento',address:'Dirección',countryCode:'País',city:'Ciudad',zone:'Zona',vehicleType:'Tipo de vehículo',vehicleBrand:'Marca',vehicleModel:'Modelo',vehiclePlate:'Placa',vehicleColor:'Color',emergencyContact:'Contacto de emergencia',commissionPercent:'Comisión del repartidor (%)'})[k]}</span><input data-driver-field="${k}" value="${esc(x[k]||'')}" disabled></label>`).join('');
    const jobRows=jobs.length?`<div class="driver-history-list">${jobs.map(j=>`<article><div><b>${j.source_type==='PACKAGE'?'📦 Paquete':'🍽️ Pedido'} ${esc(j.source_id)}</b><small>${esc(j.restaurant_name||j.customer_name||j.receiver_name||'Servicio')}</small></div><div><span>${esc(j.status)}</span><small>${Number(j.distance_km||0).toFixed(2)} km plan · ${Number(j.actual_distance_km||0).toFixed(2)} km real</small><small>${date(j.delivered_at||j.created_at)}</small></div></article>`).join('')}</div>`:'<div class="empty-box">Sin servicios registrados.</div>';
    const ratingRows=ratings.length?ratings.map(r=>`<article class="rating-row"><b>${'★'.repeat(Number(r.driver_rating||0))}${'☆'.repeat(5-Number(r.driver_rating||0))}</b><span>${esc(r.driver_comment||r.general_comment||'Sin comentario')}</span><small>${esc(r.source_type)} ${esc(r.source_id)} · ${date(r.created_at)}</small></article>`).join(''):'<div class="empty-box">Todavía no tiene evaluaciones.</div>';
    p.innerHTML=`<div class="admin-panel driver-profile-card"><div class="driver-profile-head"><div><span class="eyebrow">Ficha administrativa completa</span><h3>${esc(x.fullName)}</h3><p>${esc(x.email)}</p></div><div class="driver-head-actions"><button id="editDriver" class="driver-action view">Editar datos</button><button id="pdfDriver" class="driver-action approve">Descargar PDF</button><button id="closeDriverDetail" class="driver-action view">Cerrar</button></div></div>
    <div class="driver-admin-controls"><label><span>Comisión individual</span><div><input id="driverCommissionQuick" type="number" min="0" max="100" step="0.5" value="${Number(x.commissionPercent ?? 10)}"><b>%</b></div></label><button id="approveDriver" class="driver-action approve" type="button">Aprobar</button><button id="rejectDriver" class="driver-action reject" type="button">Rechazar</button><small>La comisión se guarda de forma individual para este repartidor.</small></div>
    <div class="driver-summary-grid"><article><span>Servicios</span><strong>${s.totalJobs||0}</strong></article><article><span>Entregados</span><strong>${s.completedJobs||0}</strong></article><article><span>Activos</span><strong>${s.activeJobs||0}</strong></article><article><span>Ganancias</span><strong>${money(s.totalEarnings,x.baseCurrency)}</strong></article><article><span>Distancia planificada</span><strong>${Number(s.plannedDistanceKm||0).toFixed(2)} km</strong></article><article><span>Distancia recorrida</span><strong>${Number(s.actualDistanceKm||0).toFixed(2)} km</strong></article><article><span>Calificación</span><strong>⭐ ${Number(s.ratingAverage||0).toFixed(2)}</strong><small>${s.ratingCount||0} evaluaciones</small></article></div>
    ${section('Datos personales y de contacto',`<form id="driverEditForm" class="driver-edit-grid">${form}<div class="driver-edit-actions hidden" id="driverEditActions"><button type="submit" class="admin-primary-btn">Guardar cambios</button><button type="button" id="cancelDriverEdit" class="driver-action view">Cancelar</button></div></form>`,true)}
    ${section('Estado, conexión y ubicación',`<div class="driver-detail-grid"><div><span>Estado administrativo</span><strong>${esc(st[x.administrativeStatus]||x.administrativeStatus)}</strong></div><div><span>Disponibilidad</span><strong>${x.isAvailable?'Disponible':'No disponible'}</strong></div><div><span>Estado operativo</span><strong>${esc(x.operationalStatus||'—')}</strong></div><div><span>Última conexión</span><strong>${date(x.lastSeenAt)}</strong></div><div><span>Última posición</span><strong>${x.lastLatitude&&x.lastLongitude?`${x.lastLatitude}, ${x.lastLongitude}`:'—'}</strong></div><div><span>Fecha de posición</span><strong>${date(x.lastLocationAt)}</strong></div></div>`)}
    ${section('Pedidos, paquetes y actividad',jobRows)}
    ${section('Ganancias y cierres',`<div class="driver-summary-grid"><article><span>Cierres</span><strong>${sett.length}</strong></article><article><span>Solicitudes</span><strong>${requests.length}</strong></article><article><span>Pendientes</span><strong>${requests.filter(r=>r.status==='PENDING').length}</strong></article><article><span>Pagados</span><strong>${sett.filter(r=>['PAID','CLOSED'].includes(r.status)).length}</strong></article></div>`)}
    ${section('Calificaciones y comentarios',ratingRows)}</div>`;
    document.getElementById('closeDriverDetail').onclick=()=>p.classList.add('hidden');document.getElementById('editDriver').onclick=()=>toggleEdit(true);document.getElementById('cancelDriverEdit').onclick=()=>show(id,true);document.getElementById('driverEditForm').onsubmit=e=>save(e,id);document.getElementById('pdfDriver').onclick=()=>pdf(x,s,jobs,ratings);document.getElementById('approveDriver').onclick=()=>changeStatus(id,'APPROVED');document.getElementById('rejectDriver').onclick=()=>changeStatus(id,'REJECTED');if(!silent)p.scrollIntoView({behavior:'smooth',block:'nearest'});
    }catch(e){p.innerHTML=`<div class="empty-box error">${esc(e.message)}</div>`}}
  async function changeStatus(id,status){const input=document.getElementById('driverCommissionQuick');const commissionPercent=Number(input?.value ?? 10);if(!Number.isFinite(commissionPercent)||commissionPercent<0||commissionPercent>100)return alert('La comisión debe estar entre 0 y 100%.');const action=status==='APPROVED'?'aprobar':'rechazar';if(!confirm(`¿Seguro que deseas ${action} este repartidor con una comisión de ${commissionPercent}%?`))return;try{await req(`/admin/drivers/${encodeURIComponent(id)}/status`,{method:'PATCH',body:JSON.stringify({status,commissionPercent})});await load(true);await show(id,true);alert(status==='APPROVED'?'Repartidor aprobado correctamente.':'Repartidor rechazado.')}catch(e){alert(e.message)}}
  function toggleEdit(on){document.querySelectorAll('[data-driver-field]').forEach(i=>i.disabled=!on);document.getElementById('driverEditActions')?.classList.toggle('hidden',!on);document.getElementById('editDriver')&&(document.getElementById('editDriver').disabled=on)}
  async function save(e,id){e.preventDefault();if(!confirm('¿Seguro que deseas actualizar los datos del repartidor?'))return;const b={};document.querySelectorAll('[data-driver-field]').forEach(i=>b[i.dataset.driverField]=i.value.trim());if(b.commissionPercent!=='')b.commissionPercent=Number(b.commissionPercent);try{await req(`/admin/drivers/${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(b)});await load(true);await show(id,true);alert('Datos actualizados correctamente.')}catch(e){alert(e.message)}}
  function pdf(x,s,jobs,ratings){const J=window.jspdf?.jsPDF;if(!J)return alert('No se pudo cargar el generador PDF.');const d=new J(),lines=[`BHUZ - Ficha del repartidor`,x.fullName,x.email,`Teléfono: ${x.phone||'—'}`,`Cédula: ${x.identityDocument||'—'}`,`Vehículo: ${[x.vehicleType,x.vehicleBrand,x.vehicleModel,x.vehiclePlate].filter(Boolean).join(' · ')}`,`Estado: ${x.administrativeStatus} / ${x.operationalStatus}`,`Servicios: ${s.totalJobs||0} | Entregados: ${s.completedJobs||0}`,`Ganancias: ${money(s.totalEarnings,x.baseCurrency)}`,`Distancia planificada: ${Number(s.plannedDistanceKm||0).toFixed(2)} km`,`Distancia recorrida: ${Number(s.actualDistanceKm||0).toFixed(2)} km`,`Calificación: ${Number(s.ratingAverage||0).toFixed(2)} (${s.ratingCount||0})`,`Historial reciente: ${jobs.length} servicios`,`Evaluaciones: ${ratings.length}`];d.setFontSize(16);d.text(lines[0],14,18);d.setFontSize(10);lines.slice(1).forEach((l,i)=>d.text(String(l),14,30+i*8));d.save(`repartidor-${x.fullName.replace(/\s+/g,'-').toLowerCase()}.pdf`)}
  function init(){if(initialized)return;initialized=true;document.getElementById('driversSearch')?.addEventListener('input',list);document.getElementById('driversStatusFilter')?.addEventListener('change',list);document.getElementById('refreshDriversBtn')?.addEventListener('click',()=>load());document.querySelector('[data-section="repartidoresSection"]')?.addEventListener('click',()=>load(true));load(true)}
  window.initAdminDrivers=init;window.refreshAdminDriversSilently=()=>load(true);
})();
